<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<beans>
    
    <!-- Ajax -->
    
    <bean id="dummyHandler" class="org.springmodules.xt.test.ajax.DummyHandler"/>
    
    <bean id="dummySubmitHandler" class="org.springmodules.xt.test.ajax.DummySubmitHandler"/>
    
    <bean id="ajaxValidationHandler" class="org.springmodules.xt.ajax.validation.DefaultValidationHandler"/>
    
    <bean id="redirectExHandler1" class="org.springmodules.xt.ajax.support.RedirectExceptionHandler">
        <property name="redirectUrl" value="/test/redirect1.html"/>
    </bean>
    
    <bean id="redirectExHandler2" class="org.springmodules.xt.ajax.support.RedirectExceptionHandler">
        <property name="redirectUrl" value="/test/redirect2.html"/>
    </bean>
    
    <bean id="ajaxInterceptor" class="org.springmodules.xt.ajax.AjaxInterceptor">
        <property name="handlerMappings">
            <props>
                <prop key="/ajax/test.action">dummyHandler</prop>
                
                <prop key="/ajax/submit.*">ajaxValidationHandler</prop>
                <prop key="/ajax/submit.action">dummySubmitHandler</prop>
                
                <prop key="/ajax/chainedSubmit.action">dummySubmitHandler, ajaxValidationHandler</prop>
            </props>
        </property>
    </bean>
    
    <bean id="ajaxExceptionResolver" class="org.springmodules.xt.ajax.AjaxExceptionHandlerResolver">
        <property name="exceptionMappings">
            <map>
                <entry key="org.springmodules.xt.ajax.support.UnsupportedEventException" value-ref="redirectExHandler1"/>
                <entry key="org.springmodules.xt.ajax.support.EventHandlingException" value-ref="redirectExHandler2"/>
            </map>
        </property>
    </bean>
    
    <!-- -->
    
</beans>